# Project Dependencies
[project]
name = "mark-1"
version = "0.1.0"
description = "A lightweight, high-level package atop FastF1 to enable Data Analysis and Modelling on race data."
readme = "README.md"
authors = [
    { name = "anilhimam17", email = "anilhimamg@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.8.3",
    "seaborn>=0.13.2",
]

# Project tools
[tool.uv]
default-groups=["dev"]

# Project Build System
[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

# Development Dependencies
[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.0",
]

# Ruff Configurations
# It's time to get a little Ruff (Get the Reference!)
# Max Code Length
[tool.ruff]
line-length=80

# Ruff Linter Configurations
[tool.ruff.lint]
select=[
    "D"
]

# Ruff Formatter Configurations
[tool.ruff.format]
# Automatic Linebreak detection
line-ending="auto"

# Quoting Style
quote-style="double"

# Enable Docstring Formatting
docstring-code-format=true
docstring-code-line-length=80

[tool.ruff.lint.pydocstyle]
convention="google"
