[project]
name = "mark-1"
version = "0.1.0"
description = "A lightweight, high-level package atop FastF1 to enable Data Analysis and Modelling on race data."
readme = "README.md"
authors = [
    { name = "anilhimam17", email = "anilhimamg@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastf1>=3.8.3",
    "plotly>=6.8.0",
    "seaborn>=0.13.2",
]

[project.scripts]
mark-1 = "mark_1:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"
